apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: {{ parameters.name }}
  description: Application created for the workshop
  annotations:
    github.com/project-slug: PawelWaj/workshop
    argocd/app-name: workshop-app
spec:
  type: service
  lifecycle: experimental
  owner: workshop-team
  system: workshop-system
