apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: ${{values.appName}}
  description: ${{values.appDescription}}
  annotations:
    github.com/project-slug: ${{values.repoUrl | replace('https://github.com/', '') | replace('.git', '')}}
    backstage.io/kubernetes-id: ${{values.appName}}
  labels:
    team: ${{values.teamName}}
spec:
  type: service
  lifecycle: experimental
  owner: group:default/guests
  system: examples
